import React from 'react';
import {useOperations} from './useOperations';
import './operations.css';
const labels:Record<string,[string,string]>={
  UPLOADING:['待上传','Awaiting upload'],QUARANTINED:['待校验','Awaiting verification'],READY:['可用','Ready'],REJECTED:['已隔离','Quarantined'],
  PENDING:['待处理','Pending'],QUEUED:['已排队','Queued'],RUNNING:['处理中','Running'],RETRY:['等待重试','Retry scheduled'],SUCCEEDED:['已完成','Completed'],DEAD:['需要恢复','Needs recovery'],
  VERIFY_FILE:['校验文件','Verify file'],VERIFY_RECEIPT:['核验交易','Verify receipt'],ORDER_PROJECTED:['同步访问与通知','Sync access and notification'],
  PAID:['付款已核验','Payment verified'],AVAILABLE:['交付状态已更新','Delivery updated'],REFUND_CREDITED:['退款可领取','Refund available'],REFUND_WITHDRAWN:['退款已领取','Refund withdrawn'],SETTLEMENT_CREDITED:['结算可领取','Settlement available'],SETTLEMENT_WITHDRAWN:['结算已领取','Settlement withdrawn'],
  UNPAID:['未确认付款','Payment unconfirmed'],CONFIRMED:['已确认','Confirmed'],NONE:['尚未入金','Not funded'],LOCKED:['本金锁定','Principal locked'],REFUND_CREDIT:['退款可领取','Refund available'],REFUNDED:['已退款','Refunded'],SETTLEMENT_CREDIT:['结算可领取','Settlement available'],SETTLED:['已结算','Settled'],REVOKED:['访问已撤销','Access revoked'],NOT_STARTED:['交付尚未开始','Delivery not started'],
};
export function OperationsApp(){
  const s=useOperations(),{lang,t,date,session,spaces,wid,tab,files,jobs,notes,activity,catalog,catalogId,series,ops,recovery,orderId,error,notice,busy,loading,current,edit,operate}=s;
  const label=(v:string)=>labels[v]?.[lang==='zh'?0:1]??v;
  const state=(v:string)=><span className={'op-state state-'+v}>{label(v)}</span>;
  const emptyState=<p className="op-empty">{t('暂无记录。仅显示当前权限范围内的真实后台记录。','No records. Only actual records within your access scope appear here.')}</p>;
  return <div className="op-shell"><a className="op-skip" href="#op-content">{t('跳到内容','Skip to content')}</a>
    <header className="op-header"><a className="op-brand" href="/">ArcBox <span>{t('工作区','Workspace')}</span></a><nav aria-label={t('工作区导航','Workspace navigation')}><a href="/app">{t('草稿与成员','Drafts & members')}</a><button onClick={()=>s.setLang(v=>v==='zh'?'en':'zh')}>{lang==='zh'?'EN':'中文'}</button>{session&&<button disabled={busy} onClick={s.logout}>{t('退出登录','Sign out')}</button>}</nav></header>
    <div className="op-intro"><div><p className="op-eyebrow">OPERATIONS / M2-C</p><h1>{t('文件、任务与后台','Files, tasks & operations')}</h1><p>{t('检查交付状态，恢复失败任务，查看操作记录。','Inspect delivery, recover failed tasks and review activity.')}</p></div><span className="op-local">{t('仅本地联调 · 无资金操作','Local integration · No funds actions')}</span></div>
    <p className="op-boundary">{t('仅支持审核过的演示文本，不开放任意文件上传。文件校验不是病毒扫描；通知仅在站内展示。','Only reviewed sample text is supported. File verification is not malware scanning. Notifications are in-app only.')}</p>
    {error&&<div role="alert" className="op-alert">{error}</div>}{notice&&<div role="status" className="op-notice">{notice}</div>}
    {!session?<section className="op-panel" id="op-content"><h2>{t('登录查看后台','Sign in to view operations')}</h2><p>{t('登录签名不授权付款；参与者无需创建商家工作区。','Signing in does not authorize payment. Participants do not need a merchant workspace.')}</p><button className="op-primary" disabled={busy||loading} onClick={()=>void s.login()}>{t('签名登录','Sign in')}</button></section>:<>
      <div className="op-controls"><label>{t('当前工作区','Current workspace')}<select aria-label={t('当前工作区','Current workspace')} value={wid} disabled={busy} onChange={e=>s.changeWorkspace(e.target.value)}><option value="">{t('个人通知与恢复','Personal notifications & recovery')}</option>{spaces.map(w=><option key={w.id} value={w.id}>{w.name} · {w.role}</option>)}</select></label><span className="op-wallet">{session.user.address}</span><button disabled={busy||loading} onClick={s.refresh}>{t('刷新状态','Refresh status')}</button></div>
      <nav className="op-tabs" aria-label={t('后台功能','Operation views')}>{([['files','文件版本','Files'],['jobs','任务与故障','Tasks'],['notifications','我的通知','Notifications'],['activity','操作日志','Activity'],['recovery','订单恢复','Recovery']] as const).map(([key,zh,en])=><button key={key} aria-current={tab===key?'page':undefined} disabled={busy} onClick={()=>{if(tab!==key)s.switchTab(key);}}>{t(zh,en)}</button>)}</nav>
      <main id="op-content" aria-busy={loading}>
        {ops&&wid&&<div className="op-metrics"><div><span>{t('文件存储','File storage')}</span><strong>{ops.storageConfigured?t('已绑定（本地）','Bound (local)'):t('未绑定','Unavailable')}</strong></div><div><span>{t('任务队列','Task queue')}</span><strong>{ops.queueConfigured?t('已绑定（本地）','Bound (local)'):t('未绑定','Unavailable')}</strong></div><div><span>{t('待恢复任务','Tasks needing recovery')}</span><strong>{ops.counts.find(c=>c.state==='DEAD')?.count??0}</strong></div></div>}
        {loading&&<p role="status">{t('正在读取后台记录…','Loading records…')}</p>}
        {!wid&&['files','jobs','activity'].includes(tab)&&<section className="op-panel"><h2>{t('选择工作区','Select a workspace')}</h2><p>{t('文件和任务属于工作区；买家可直接使用“我的通知”和“订单恢复”。','Files and tasks belong to a workspace. Buyers can use Notifications and Recovery directly.')}</p><a href="/app">{t('管理或创建工作区','Manage or create a workspace')}</a></section>}
        {tab==='files'&&wid&&<section className="op-panel"><div className="op-section-title"><h2>{t('不可变文件版本','Immutable file versions')}</h2><span>{current?.role}</span></div>{edit?<div className="op-upload"><label>{t('受控样本','Reviewed sample')}<select aria-label={t('受控样本','Reviewed sample')} disabled={busy} value={catalogId} onChange={e=>s.setCatalogId(e.target.value)}>{catalog.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{t('版本系列','Version series')}<select aria-label={t('版本系列','Version series')} disabled={busy} value={series} onChange={e=>s.setSeries(e.target.value)}><option value="">{t('新建系列','New series')}</option>{files.items.filter((f,i,a)=>a.findIndex(x=>x.seriesId===f.seriesId)===i).map(f=><option key={f.seriesId} value={f.seriesId}>{f.name} · {f.seriesId.slice(0,8)}</option>)}</select></label><button className="op-primary" disabled={busy||!catalog.length} onClick={s.importFile}>{t('导入受控样本','Import reviewed sample')}</button></div>:<p className="op-permission">{t('当前角色只可查看文件。上传需 owner 或 editor。','Read-only files. Upload requires owner or editor.')}</p>}
          <p>{t('旧订单固定使用购买时的文件版本。后续版本不会替换旧文件；本阶段不提供删除入口。','Existing orders retain the version recorded in their rules. Later versions do not replace old files. Deletion is unavailable in this stage.')}</p>
          {!loading&&!files.items.length&&emptyState}<div className="op-records">{files.items.map(f=><article className="op-record" key={f.id}><div className="op-row"><strong>{f.name}</strong>{state(f.state)}</div><p>{t('版本','Version')} {f.version} · {f.bytes} bytes · {date(f.createdAt)}</p><details><summary>{t('版本校验信息','Version integrity details')}</summary><p>ID <code>{f.id}</code></p><p>SHA-256 <code>{f.sha256}</code></p></details>{edit&&f.state==='UPLOADING'&&f.uploadUntil>Date.now()&&<button disabled={busy} onClick={()=>s.continueUpload(f)}>{t('继续上传此版本','Resume this upload')}</button>}{edit&&f.state==='QUARANTINED'&&<button disabled={busy} onClick={()=>s.ensureFileTask(f)}>{t('确认校验任务','Ensure verification task')}</button>}</article>)}</div>{files.nextCursor!==null&&<button disabled={busy} onClick={()=>s.more('files')}>{t('加载更多文件','Load more files')}</button>}
        </section>}
        {tab==='jobs'&&wid&&<section className="op-panel"><div className="op-section-title"><h2>{t('任务与故障恢复','Tasks & failure recovery')}</h2>{operate&&<button className="op-primary" disabled={busy} onClick={s.run}>{t('运行待办任务','Run pending tasks')}</button>}</div><p>{t('重试只处理文件、索引或站内通知，不会重新发起付款。失败任务保留原因；完整性失败不能强制放行。','Retries process files, indexing or in-app notifications, not payments. Failed tasks retain reasons. Integrity failures cannot be overridden.')}</p>
          {!loading&&!jobs.items.length&&emptyState}<div className="op-records">{jobs.items.map(j=><article className="op-record" key={j.id}><div className="op-row"><strong>{label(j.type)}</strong>{state(j.state)}</div><p>{t('执行次数','Attempts')} {j.attempts}/5 · {t('分发次数','Dispatches')} {j.dispatch_attempts}/5 · {date(j.created_at)}</p><code>{j.id}</code>{j.last_error&&<p className="op-error-code">{j.last_error}</p>}{operate&&j.state==='DEAD'&&j.last_error!=='FILE_INTEGRITY_FAILURE'&&<button disabled={busy} onClick={()=>s.retry(j)}>{t('重试任务','Retry task')}</button>}</article>)}</div>{jobs.nextCursor!==null&&<button disabled={busy} onClick={()=>s.more('jobs')}>{t('加载更多任务','Load more tasks')}</button>}
          {!!ops?.incidents.length&&<details><summary>{t('链上同步异常','Indexer incidents')}</summary>{ops.incidents.map(x=><p key={x.id}>{x.code} · {date(x.created_at)}</p>)}</details>}
        </section>}
        {tab==='notifications'&&<section className="op-panel"><h2>{t('我的站内通知','My in-app notifications')}</h2><p>{t('通知记录过去发生的事件，不代表订单此刻仍处于同一状态。请打开订单恢复核验当前状态。','Notifications describe historical events. Open Recovery to verify the current order state.')}</p>{!loading&&!notes.items.length&&emptyState}<div className="op-records">{notes.items.map(n=><article className="op-record" key={n.id}><div className="op-row"><strong>{label(n.code)}</strong><span>{n.read_at?t('已读','Read'):t('未读','Unread')}</span></div><p>{date(n.created_at)}</p><code>{n.order_id}</code><div className="op-row"><button disabled={busy} onClick={()=>s.openRecovery(n.order_id)}>{t('查看订单恢复','Open recovery')}</button>{!n.read_at&&<button disabled={busy} onClick={()=>s.markRead(n)}>{t('标为已读','Mark read')}</button>}</div></article>)}</div>{notes.nextCursor!==null&&<button disabled={busy} onClick={()=>s.more('notifications')}>{t('加载更多通知','Load more notifications')}</button>}</section>}
        {tab==='activity'&&wid&&<section className="op-panel"><h2>{t('操作日志','Operation log')}</h2><p>{t('记录任务、上传和访问操作；不展示密钥、签名、文件正文或下载令牌。','Records task, upload and access operations without keys, signatures, file contents or download tokens.')}</p>{!loading&&!activity.items.length&&emptyState}{activity.items.map(a=><article className="op-record" key={a.id}><div className="op-row"><strong>{a.action}</strong><span>{date(a.created_at)}</span></div><code>{a.entity_id}</code>{a.code&&<p>{a.code}</p>}</article>)}{activity.nextCursor!==null&&<button disabled={busy} onClick={()=>s.more('activity')}>{t('加载更多日志','Load more activity')}</button>}</section>}
        {tab==='recovery'&&<section className="op-panel"><h2>{t('订单与文件恢复','Order & file recovery')}</h2><p>{t('状态不确定时先核验，不要重复付款。只查询你参与或有管理权限的订单。','Verify uncertain status before paying again. Only orders you participate in or can manage are accessible.')}</p><form className="op-recovery-form" onSubmit={e=>{e.preventDefault();s.recover();}}><label>{t('订单 ID','Order ID')}<input aria-label={t('订单 ID','Order ID')} value={orderId} maxLength={36} required disabled={busy} onChange={e=>s.changeOrder(e.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/></label><button className="op-primary" disabled={busy}>{t('核验并恢复','Verify status')}</button></form>{recovery&&<div className="op-recovery-result"><h3>{t('当前后台核验结果','Current verified projection')}</h3><dl><dt>{t('付款','Payment')}</dt><dd>{label(recovery.order.paymentState)}</dd><dt>{t('资金分类','Funds category')}</dt><dd>{label(recovery.order.fundsState)}</dd><dt>{t('交付','Delivery')}</dt><dd>{label(recovery.order.deliveryState)}</dd><dt>{t('文件版本','File version')}</dt><dd>{recovery.file?`${recovery.file.name} · v${recovery.file.version}`:'—'}</dd></dl>{recovery.entitlement&&<p>{t('访问保留至','Access retained until')} {date(recovery.entitlement.retention_until)}</p>}{recovery.downloadEligible?<button className="op-primary" disabled={busy} onClick={s.saveFile}>{t('安全下载文件','Download securely')}</button>:<p className="op-permission">{t('当前没有可用下载权限。退款、文件故障或保留期届满都可能阻止下载。','Download access is unavailable. Refunds, file failures or retention expiry can prevent access.')}</p>}<p>{t('可领取金额不代表已经到账。本页面不会发起资金交易。','Available-to-claim funds are not yet received. This page never initiates a funds transaction.')}</p></div>}</section>}
      </main></>}
  </div>;
}
