/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.demo.jsonc --include-runtime=false workers/demo/worker-configuration.d.ts` (hash: 26877513a50f2a043beb3ed0a1b31286)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	APP_ENV: "demo";
	PAYMENTS_ENABLED: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "PAYMENTS_ENABLED">> {}
}
